# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=64)),
                ('uuid', models.CharField(default='', max_length=64)),
                ('model', models.CharField(default='', max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(default='', max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='member',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='po.Member'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('token', 'uuid')]),
        ),
    ]
